services:
  backend:
    build:
      context: ./
      target: backend-prod
    environment:
      - DATABASE_HOST=database
      - DATABASE_USER=root
      - DATABASE_PASSWORD=mysql
    depends_on:
      database:
        condition: service_healthy
    ports:
      - 3000:3000

  frontend:
    build:
      context: ./
      target: frontend-prod
    ports:
      - 80:80

  database:
    image: mariadb:12
    environment:
      MARIADB_ROOT_PASSWORD: mysql
    volumes:
      - database-data:/var/lib/mariadb
    healthcheck:
      test: ["CMD", "mariadb-admin", "-uroot", "-pmysql", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 3306:3306

volumes:
  database-data:
